//
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
//
// dphi.cpp
//
// Code generation for function 'dphi'
//

// Include files
#include "dphi.h"
#include <cmath>

// Function Definitions
namespace model {
double dphi(double dp0, double dx0, double dy0, double l, double phi, double r,
            double th)
{
  // DPHI
  //     OUT1 = DPHI(DP0,DX0,DY0,L,PHI,R,TH)
  //     This function was generated by the Symbolic Math Toolbox version 9.1.
  //     09-Sep-2022 17:49:00
  return (((dp0 * r - dy0 * std::cos(th)) + dx0 * std::sin(th)) +
          dp0 * l * std::cos(phi)) /
         r;
}

} // namespace model

// End of code generation (dphi.cpp)
