//
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
//
// fk_psi.cpp
//
// Code generation for function 'fk_psi'
//

// Include files
#include "fk_psi.h"
#include "rt_nonfinite.h"

// Function Definitions
namespace model {
double fk_psi(double phi, double th)
{
  // FK_PSI
  //     PSI = FK_PSI(PHI,TH)
  //     This function was generated by the Symbolic Math Toolbox version 9.1.
  //     04-Sep-2022 21:54:38
  return phi + th;
}

} // namespace model

// End of code generation (fk_psi.cpp)
