//
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
//
// fk_x.cpp
//
// Code generation for function 'fk_x'
//

// Include files
#include "fk_x.h"
#include "rt_nonfinite.h"
#include <cmath>

// Function Definitions
namespace model {
double fk_x(double l, double phi, double r, double th)
{
  // FK_X
  //     X = FK_X(L,PHI,R,TH)
  //     This function was generated by the Symbolic Math Toolbox version 9.1.
  //     04-Sep-2022 21:54:38
  return l * std::cos(phi + th) + r * std::cos(th);
}

} // namespace model

// End of code generation (fk_x.cpp)
