//
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
//
// fk_y.cpp
//
// Code generation for function 'fk_y'
//

// Include files
#include "fk_y.h"
#include "rt_nonfinite.h"
#include <cmath>

// Function Definitions
namespace model {
double fk_y(double l, double phi, double r, double th)
{
  // FK_Y
  //     Y = FK_Y(L,PHI,R,TH)
  //     This function was generated by the Symbolic Math Toolbox version 9.1.
  //     04-Sep-2022 21:54:38
  return l * std::sin(phi + th) + r * std::sin(th);
}

} // namespace model

// End of code generation (fk_y.cpp)
