//
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
//
// ik_r.cpp
//
// Code generation for function 'ik_r'
//

// Include files
#include "ik_r.h"
#include "ik_r_rtwutil.h"
#include "rt_nonfinite.h"
#include <cmath>

// Function Definitions
namespace model {
void ik_r(double l, double p0, double x0, double b_y0, double out1[2])
{
  double t2;
  // IK_R
  //     OUT1 = IK_R(L,P0,X0,Y0)
  //     This function was generated by the Symbolic Math Toolbox version 9.1.
  //     04-Sep-2022 21:54:38
  t2 = std::cos(p0);
  t2 = (t2 + 1.0) *
       std::sqrt(1.0 / rt_powd_snf(std::cos(p0 / 2.0), 4.0) *
                 ((((l * l + x0 * x0) + b_y0 * b_y0) + -(l * t2 * x0 * 2.0)) +
                  -(l * std::sin(p0) * b_y0 * 2.0))) /
       2.0;
  out1[0] = -t2;
  out1[1] = t2;
}

} // namespace model

// End of code generation (ik_r.cpp)
