//
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
//
// r.cpp
//
// Code generation for function 'r'
//

// Include files
#include "r.h"
#include "r_rtwutil.h"
#include "rt_nonfinite.h"
#include <cmath>

// Function Definitions
namespace model {
void r(double l, double p0, double x0, double b_y0, double out1[2])
{
  double t2;
  // R
  //     OUT1 = R(L,P0,X0,Y0)
  //     This function was generated by the Symbolic Math Toolbox version 9.1.
  //     27-Aug-2022 21:23:28
  t2 = std::cos(p0);
  t2 = (t2 + 1.0) *
       std::sqrt(1.0 / rt_powd_snf(std::cos(p0 / 2.0), 4.0) *
                 ((((l * l + x0 * x0) + b_y0 * b_y0) + -(l * t2 * x0 * 2.0)) +
                  -(l * std::sin(p0) * b_y0 * 2.0))) /
       2.0;
  out1[0] = -t2;
  out1[1] = t2;
}

} // namespace model

// End of code generation (r.cpp)
