robot_joint_state_generator:
  ros__parameters:
    velocity_ratio:
      x: 0.05
      y: 0.05
      z: 0.03
      psi: 0.05
    xy_auto:
      ratio: 2.0
      max_speed: 0.35
    psi_auto:
      ratio: 2.0
      max_speed: 0.75
    z_auto:
      ratio: 2.0
      max_speed: 0.25
      approach_offset: 0.03

# world_coord_controller:
#   ros__parameters:

joint_state_publisher:
  ros__parameters:
    rate: 50
    source_list: ["manual_joint"]

joy_node:
  ros__parameters:
    autorepeat_rate: 50.0 # [Hz]
    # coalesce_interval_ms: 20  # [ms]


motor_controller:
  ros__parameters:
    sleep_time: 5
    usb_device:
      left_right: usb-FTDI_FT232R_USB_UART_AQ0287SJ-if00-port0
      theta_z: usb-FTDI_FT232R_USB_UART_AQ027PCT-if00-port0
    right:
      id: 0x06
      dir: 1
      Kp: 1.5
      max_speed: 10.0
    left:
      id: 0x09
      dir: -1
      Kp: 3.0
      max_speed: 10.0
    theta:
      id: 0x06
      dir: 1
      max_current: 3.0
      Kp_pos: 2.0
      Kp_vel: 0.8
      observer:
        K: 5.4
        pole1: -10.0
        pole2: -8.0
    z:
      id: 0x09
      dir: -1
      Kp: 4.0
      max_speed: 10.0

hand_tool_manager:
  ros__parameters:
    usb_device: 
      pump_arduino: usb-Arduino_LLC_Arduino_Nano_Every_1FDD8FBD515146544E4B2020FF0E1B42-if00

rapid_hand_controller_node:
  ros__parameters:
    usb_device: 
      rapid_arduino: usb-Arduino_LLC_Arduino_Nano_Every_5F7BB2275153314639202020FF0D3920-if00 