world_coord_controller:
  ros__parameters:
    velocity_ratio:
      normal:
        x: 0.2
        y: 0.2
        z: 0.1
        psi: 0.3
      adjust:
        x: 0.05
        y: 0.05
        z: 0.04
        psi: 0.05
    xy_auto:
      ratio: 1.5
      max_speed: 0.2
    psi_auto:
      ratio: 2.0
      max_speed: 0.8
    z_auto:
      ratio: 2.0
      max_speed: 0.3
      approach_offset: 0.03

joint_state_publisher:
  ros__parameters:
    rate: 50
    source_list: ["manual_joint"]

joy_node:
  ros__parameters:
    autorepeat_rate: 50.0 # [Hz]
    # coalesce_interval_ms: 20  # [ms]

hand_tool_manager:
  ros__parameters:
    usb_device:
      pump_arduino: "ttyACM0"

motor_controller:
  ros__parameters:
    sleep_time: 5
    usb_device:
      left_right: usb-FTDI_FT232R_USB_UART_AQ0287SJ-if00-port0
      theta_z: usb-FTDI_FT232R_USB_UART_AQ027PCT-if00-port0
    right:
      id: 0x06
      dir: 1
      Kp: 3.0
      max_speed: 10.0
    left:
      id: 0x09
      dir: -1
      Kp: 3.0
      max_speed: 10.0
    theta:
      id: 0x06
      dir: 1
      max_current: 3.0
      Kp_pos: 3.0
      Kp_vel: 1.0
      observer:
        K: 5.4
        pole1: -10.0
        pole2: -8.0
    z:
      id: 0x09
      dir: -1
      Kp: 4.0
      max_speed: 10.0
